### PR TITLE
HA: test fence_scsi

### PR DESCRIPTION
**Pull request by lucaskanashiro**

### CODE REVIEW

**Comment by lucaskanashiro** [comment]
The last commit needs to be removed once the new fence-agents package lands in impish:

https://code.launchpad.net/~lucaskanashiro/ubuntu/+source/fence-agents/+git/fence-agents/+merge/404990

**Review by paride — CHANGES_REQUESTED** [review]
The logic here LGTM and the test passes fine on my laptop, but it does not on a Bionic machine (one of our Jenkins nodes). Log excerpt:
```
+ IP_VM_SERVICES=192.168.122.105
+ block_until_cloud_init_is_done 192.168.122.105
+ NODE=192.168.122.105
+ run_command_in_node 192.168.122.105 'echo '\''debconf debconf/frontend select Noninteractive'\'' | sudo debconf-set-selections'
+ NODE=192.168.122.105
+ CMD='echo '\''debconf debconf/frontend select Noninteractive'\'' | sudo debconf-set-selections'
+ ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR ubuntu@192.168.122.105 'echo '\''debconf debconf/frontend select Noninteractive'\'' | sudo debconf-set-selections'
ssh: connect to host 192.168.122.105 port 22: Connection refused
+ exit 1
error: failed to get domain 'ha-agent-virsh-impish-fence_scsi-node01'
error: Domain not found: no domain with matching name 'ha-agent-virsh-impish-fence_scsi-node01'
```
On the same machine `fence_virsh_test.sh` passes fine, so the problem seems to be specific to this new test and not about the general VM setup.

**Comment by lucaskanashiro** [comment]
@paride after the last commit I added I ran the test 5 times in dugtrio and all the attempts passed.

**Comment by paride** [comment]
Thanks! Having one last look and I'll merge.

**Pull request merged**
