### PR TITLE
Add metric server bugs

### PR DESCRIPTION
**Pull request by cpaelzer**
This is a tool from @mclemenceau that I extended to put data into google and here changed it to work with anonymous user and to be in the script directory used for our automation jobs.

### CODE REVIEW

**Comment by cpaelzer** [comment]
Currently this works, up to the point when it gets stuck authenticating with gspread.
I think to fully make it work we will need to request [this](https://support.google.com/a/answer/2589954?hl=en) in the firewall rules.

**Comment by cpaelzer** [comment]
We passed the firewall issues, since this was all http[s] proxies were enough.
I'll ping once it fully worked to then review and merge.

**Comment by cpaelzer** [comment]
And with https://jenkins.canonical.com/server-team/view/metrics/job/metric-server-bugs/9/ we have the first good run.
This would be ready for review and merge.

**Review by paride — APPROVED** [review]
LGTM

**Pull request merged**
