### PR TITLE
[HA] Fix some failures reported by Jenkins

### PR DESCRIPTION
**Pull request by lucaskanashiro**

### CODE REVIEW

**Comment by lucaskanashiro** [comment]
@paride could you try to run a job from this branch to see if the failure got fixed? I couldn't reproduce the failure locally, and it is still working with the proposed changes for me.

**Comment by paride** [comment]
Hi @lucaskanashiro, I just tried but apparently this change isn't enough :/

**Comment by lucaskanashiro** [comment]
@paride now I tested this branch in `dugtrio` and all the tests are passing again. Could you retry the job?

**Review by paride — APPROVED** [review]
The job now passes fine on Jenkins and the changes LGTM.

**Pull request merged**
