### PR TITLE
amazon-ec2-net-utils: init commit

### PR DESCRIPTION
**Pull request by mitchdz**
These tests are very much still WIP, but I'd like to see if it's fine for me to store this test script in this repo. I'm also thinking about adding my `ec2-hibinit-agent` test to this repo. These are cloud specific packages, but I think it makes sense to store them in this repository for now until there are enough cloud packages.

Alternatively I could add the cloud packages into a `./cloud/` or `./cpc/` directory. This way it'd be easy to find the test scripts from both the cpc/server team.

thoughts?

### CODE REVIEW

**Comment by lucaskanashiro** [comment]
Hey @mitchdz o/

I believe adding your test scripts here is a good idea. As you suggested, I think it would be better if you put them inside a directory, `public-cloud` might be a meaningful name.

I did not try to run the test myself, but in a initial review of any bash script I usually run `shellcheck` to  see if there is any improvements that can be implemented, and in this case I got some warnings:

```
$ shellcheck test-amazon-ec2-net-utils.sh 

In test-amazon-ec2-net-utils.sh line 6:
source config.sh
       ^-------^ SC1091: Not following: config.sh was not specified as input (see shellcheck -x).


In test-amazon-ec2-net-utils.sh line 9:
ssh_key="~/.ssh/${aws_keyname}.pem"
         ^-----^ SC2088: Tilde does not expand in quotes. Use $HOME.
                ^------------^ SC2154: aws_keyname is referenced but not assigned.


In test-amazon-ec2-net-utils.sh line 18:
    for ((i = 1; i <= $max_ssh_attempts; i++)); do
                      ^---------------^ SC2004: $/${} is unnecessary on arithmetic variables.


In test-amazon-ec2-net-utils.sh line 19:
        ssh $ssh_flags -i $ssh_key ubuntu@${ipaddr} exit
            ^--------^ SC2086: Double quote to prevent globbing and word splitting.
                          ^------^ SC2086: Double quote to prevent globbing and word splitting.
                                          ^-------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
        ssh "$ssh_flags" -i "$ssh_key" ubuntu@"${ipaddr}" exit


In test-amazon-ec2-net-utils.sh line 20:
        if [ $? -eq 0 ]; then
             ^-- SC2181: Check exit code directly with e.g. 'if mycmd;', not indirectly with $?.


In test-amazon-ec2-net-utils.sh line 46:
    --region ${aws_region} \
             ^-----------^ SC2154: aws_region is referenced but not assigned.
             ^-----------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
    --region "${aws_region}" \


In test-amazon-ec2-net-utils.sh line 47:
    --image-id ${aws_ami} \
               ^--------^ SC2154: aws_ami is referenced but not assigned.
               ^--------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
    --image-id "${aws_ami}" \


In test-amazon-ec2-net-utils.sh line 49:
    --instance-type ${aws_instance_type} \
                    ^------------------^ SC2154: aws_instance_type is referenced but not assigned.
                    ^------------------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
    --instance-type "${aws_instance_type}" \


In test-amazon-ec2-net-utils.sh line 50:
    --key-name ${aws_keyname} \
               ^------------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
    --key-name "${aws_keyname}" \


In test-amazon-ec2-net-utils.sh line 51:
    --security-group-ids ${aws_security_group} \
                         ^-------------------^ SC2154: aws_security_group is referenced but not assigned.
                         ^-------------------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
    --security-group-ids "${aws_security_group}" \


In test-amazon-ec2-net-utils.sh line 52:
    --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=${aws_instance_name}}]" \
                                                                      ^------------------^ SC2154: aws_instance_name is referenced but not assigned.


In test-amazon-ec2-net-utils.sh line 57:
  --region $aws_region \
           ^---------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
  --region "$aws_region" \


In test-amazon-ec2-net-utils.sh line 58:
  --instance-ids $instance_id \
                 ^----------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
  --instance-ids "$instance_id" \


In test-amazon-ec2-net-utils.sh line 64:
  --region $aws_region \
           ^---------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
  --region "$aws_region" \


In test-amazon-ec2-net-utils.sh line 65:
  --subnet-id $subnet_id \
              ^--------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
  --subnet-id "$subnet_id" \


In test-amazon-ec2-net-utils.sh line 67:
  --groups $aws_security_group \
           ^-----------------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
  --groups "$aws_security_group" \


In test-amazon-ec2-net-utils.sh line 72:
  --region $aws_region \
           ^---------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
  --region "$aws_region" \


In test-amazon-ec2-net-utils.sh line 73:
  --network-interface-id $eni_id \
                         ^-----^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
  --network-interface-id "$eni_id" \


In test-amazon-ec2-net-utils.sh line 74:
  --instance-id $instance_id \
                ^----------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
  --instance-id "$instance_id" \


In test-amazon-ec2-net-utils.sh line 78:
aws ec2 wait instance-running --region $aws_region --instance-ids $instance_id
                                       ^---------^ SC2086: Double quote to prevent globbing and word splitting.
                                                                  ^----------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
aws ec2 wait instance-running --region "$aws_region" --instance-ids "$instance_id"


In test-amazon-ec2-net-utils.sh line 79:
ipaddr=$(aws ec2 describe-instances --instance-ids $instance_id --region $aws_region \
                                                   ^----------^ SC2086: Double quote to prevent globbing and word splitting.
                                                                         ^---------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
ipaddr=$(aws ec2 describe-instances --instance-ids "$instance_id" --region "$aws_region" \


In test-amazon-ec2-net-utils.sh line 83:
wait_for_ssh $ipaddr
             ^-----^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
wait_for_ssh "$ipaddr"


In test-amazon-ec2-net-utils.sh line 86:
ssh $ssh_flags -i $ssh_key ubuntu@${ipaddr}
    ^--------^ SC2086: Double quote to prevent globbing and word splitting.
                  ^------^ SC2086: Double quote to prevent globbing and word splitting.
                                  ^-------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
ssh "$ssh_flags" -i "$ssh_key" ubuntu@"${ipaddr}"


In test-amazon-ec2-net-utils.sh line 89:
ssh $ssh_flags -i $ssh_key ubuntu@${ipaddr} \
    ^--------^ SC2086: Double quote to prevent globbing and word splitting.
                  ^------^ SC2086: Double quote to prevent globbing and word splitting.
                                  ^-------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
ssh "$ssh_flags" -i "$ssh_key" ubuntu@"${ipaddr}" \


In test-amazon-ec2-net-utils.sh line 93:
ssh $ssh_flags -i $ssh_key ubuntu@${ipaddr} \
    ^--------^ SC2086: Double quote to prevent globbing and word splitting.
                  ^------^ SC2086: Double quote to prevent globbing and word splitting.
                                  ^-------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
ssh "$ssh_flags" -i "$ssh_key" ubuntu@"${ipaddr}" \


In test-amazon-ec2-net-utils.sh line 97:
ssh $ssh_flags -i $ssh_key ubuntu@${ipaddr} \
    ^--------^ SC2086: Double quote to prevent globbing and word splitting.
                  ^------^ SC2086: Double quote to prevent globbing and word splitting.
                                  ^-------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
ssh "$ssh_flags" -i "$ssh_key" ubuntu@"${ipaddr}" \


In test-amazon-ec2-net-utils.sh line 101:
ssh $ssh_flags -i $ssh_key ubuntu@${ipaddr} \
    ^--------^ SC2086: Double quote to prevent globbing and word splitting.
                  ^------^ SC2086: Double quote to prevent globbing and word splitting.
                                  ^-------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
ssh "$ssh_flags" -i "$ssh_key" ubuntu@"${ipaddr}" \


In test-amazon-ec2-net-utils.sh line 103:
ssh $ssh_flags -i $ssh_key ubuntu@${ipaddr} \
    ^--------^ SC2086: Double quote to prevent globbing and word splitting.
                  ^------^ SC2086: Double quote to prevent globbing and word splitting.
                                  ^-------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
ssh "$ssh_flags" -i "$ssh_key" ubuntu@"${ipaddr}" \


In test-amazon-ec2-net-utils.sh line 107:
ssh $ssh_flags -i $ssh_key ubuntu@${ipaddr} 'sudo ip a'
    ^--------^ SC2086: Double quote to prevent globbing and word splitting.
                  ^------^ SC2086: Double quote to prevent globbing and word splitting.
                                  ^-------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
ssh "$ssh_flags" -i "$ssh_key" ubuntu@"${ipaddr}" 'sudo ip a'


In test-amazon-ec2-net-utils.sh line 108:
ssh $ssh_flags -i $ssh_key ubuntu@${ipaddr} 'sudo ip rule show'
    ^--------^ SC2086: Double quote to prevent globbing and word splitting.
                  ^------^ SC2086: Double quote to prevent globbing and word splitting.
                                  ^-------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
ssh "$ssh_flags" -i "$ssh_key" ubuntu@"${ipaddr}" 'sudo ip rule show'


In test-amazon-ec2-net-utils.sh line 109:
ssh $ssh_flags -i $ssh_key ubuntu@${ipaddr} 'sudo ip route show'
    ^--------^ SC2086: Double quote to prevent globbing and word splitting.
                  ^------^ SC2086: Double quote to prevent globbing and word splitting.
                                  ^-------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
ssh "$ssh_flags" -i "$ssh_key" ubuntu@"${ipaddr}" 'sudo ip route show'


In test-amazon-ec2-net-utils.sh line 110:
ssh $ssh_flags -i $ssh_key ubuntu@${ipaddr} 'sudo ip route show table 10001'
    ^--------^ SC2086: Double quote to prevent globbing and word splitting.
                  ^------^ SC2086: Double quote to prevent globbing and word splitting.
                                  ^-------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
ssh "$ssh_flags" -i "$ssh_key" ubuntu@"${ipaddr}" 'sudo ip route show table 10001'


In test-amazon-ec2-net-utils.sh line 111:
ssh $ssh_flags -i $ssh_key ubuntu@${ipaddr} 'sudo ip route show table 10002'
    ^--------^ SC2086: Double quote to prevent globbing and word splitting.
                  ^------^ SC2086: Double quote to prevent globbing and word splitting.
                                  ^-------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
ssh "$ssh_flags" -i "$ssh_key" ubuntu@"${ipaddr}" 'sudo ip route show table 10002'


In test-amazon-ec2-net-utils.sh line 113:
version=$(ssh $ssh_flags -i $ssh_key ubuntu@${ipaddr} \
              ^--------^ SC2086: Double quote to prevent globbing and word splitting.
                            ^------^ SC2086: Double quote to prevent globbing and word splitting.
                                            ^-------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
version=$(ssh "$ssh_flags" -i "$ssh_key" ubuntu@"${ipaddr}" \

For more information:
  https://www.shellcheck.net/wiki/SC2088 -- Tilde does not expand in quotes. ...
  https://www.shellcheck.net/wiki/SC2154 -- aws_ami is referenced but not ass...
  https://www.shellcheck.net/wiki/SC1091 -- Not following: config.sh was not ...
```

I hope that is helpful.

**Comment by mitchdz** [comment]
Thanks Lucas! And yes, the script is in a rough state and I'm actively improving it. Will be updating it shortly, but wanting to get feedback on if this will be a good home for it.

**Comment by mitchdz** [comment]
Also thanks for the `shellcheck` reminder. I'll make sure there's a clean `shellcheck` and create a `cpc` directory soon :)

**Comment by mitchdz** [comment]
now a clean `shellcheck ./test-amazon-ec2-net-utils.sh`. Refactored a bunch of the code.

the actual test script itself is still a WIP and will change soon, but this is just a placeholder for now with the current work. Still some more refactoring/testing planned.

**Comment by mitchdz** [comment]
okay updated it with an actually working test case. Please do not run shellcheck on these scripts at this time. You will cry.

Cleanup for linting can be done later, for now these scripts work to properly test the package in an E2E flow.

**Comment by lucaskanashiro** [comment]
Thanks @mitchdz , it looks way better now :)

I did not test it, I'll let this for you. Merging your changes.

**Pull request merged**
